/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateGiftingRouteImport } from './routes/corporate-gifting'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CataloguePrintRouteImport } from './routes/catalogue.print'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsCategoryRouteImport } from './routes/collections.$category'
import { Route as OccasionsIndexRouteImport } from './routes/occasions.index'
import { Route as OccasionsOccasionRouteImport } from './routes/occasions.$occasion'
import { Route as ProductsProductRouteImport } from './routes/products.$product'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateGiftingRoute = CorporateGiftingRouteImport.update({
  id: '/corporate-gifting',
  path: '/corporate-gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CataloguePrintRoute = CataloguePrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => CatalogueRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategoryRoute = CollectionsCategoryRouteImport.update({
  id: '/collections/$category',
  path: '/collections/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsIndexRoute = OccasionsIndexRouteImport.update({
  id: '/occasions/',
  path: '/occasions/',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsOccasionRoute = OccasionsOccasionRouteImport.update({
  id: '/occasions/$occasion',
  path: '/occasions/$occasion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductRoute = ProductsProductRouteImport.update({
  id: '/products/$product',
  path: '/products/$product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/contact': typeof ContactRoute
  '/corporate-gifting': typeof CorporateGiftingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/catalogue/print': typeof CataloguePrintRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/occasions/$occasion': typeof OccasionsOccasionRoute
  '/products/$product': typeof ProductsProductRoute
  '/collections/': typeof CollectionsIndexRoute
  '/occasions/': typeof OccasionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/contact': typeof ContactRoute
  '/corporate-gifting': typeof CorporateGiftingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/catalogue/print': typeof CataloguePrintRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/occasions/$occasion': typeof OccasionsOccasionRoute
  '/products/$product': typeof ProductsProductRoute
  '/collections': typeof CollectionsIndexRoute
  '/occasions': typeof OccasionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/contact': typeof ContactRoute
  '/corporate-gifting': typeof CorporateGiftingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/catalogue/print': typeof CataloguePrintRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/occasions/$occasion': typeof OccasionsOccasionRoute
  '/products/$product': typeof ProductsProductRoute
  '/collections/': typeof CollectionsIndexRoute
  '/occasions/': typeof OccasionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catalogue'
    | '/contact'
    | '/corporate-gifting'
    | '/privacy-policy'
    | '/terms'
    | '/catalogue/print'
    | '/collections/$category'
    | '/occasions/$occasion'
    | '/products/$product'
    | '/collections/'
    | '/occasions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalogue'
    | '/contact'
    | '/corporate-gifting'
    | '/privacy-policy'
    | '/terms'
    | '/catalogue/print'
    | '/collections/$category'
    | '/occasions/$occasion'
    | '/products/$product'
    | '/collections'
    | '/occasions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catalogue'
    | '/contact'
    | '/corporate-gifting'
    | '/privacy-policy'
    | '/terms'
    | '/catalogue/print'
    | '/collections/$category'
    | '/occasions/$occasion'
    | '/products/$product'
    | '/collections/'
    | '/occasions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CatalogueRoute: typeof CatalogueRouteWithChildren
  ContactRoute: typeof ContactRoute
  CorporateGiftingRoute: typeof CorporateGiftingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  CollectionsCategoryRoute: typeof CollectionsCategoryRoute
  OccasionsOccasionRoute: typeof OccasionsOccasionRoute
  ProductsProductRoute: typeof ProductsProductRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  OccasionsIndexRoute: typeof OccasionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-gifting': {
      id: '/corporate-gifting'
      path: '/corporate-gifting'
      fullPath: '/corporate-gifting'
      preLoaderRoute: typeof CorporateGiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/print': {
      id: '/catalogue/print'
      path: '/print'
      fullPath: '/catalogue/print'
      preLoaderRoute: typeof CataloguePrintRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$category': {
      id: '/collections/$category'
      path: '/collections/$category'
      fullPath: '/collections/$category'
      preLoaderRoute: typeof CollectionsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions/': {
      id: '/occasions/'
      path: '/occasions'
      fullPath: '/occasions/'
      preLoaderRoute: typeof OccasionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions/$occasion': {
      id: '/occasions/$occasion'
      path: '/occasions/$occasion'
      fullPath: '/occasions/$occasion'
      preLoaderRoute: typeof OccasionsOccasionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$product': {
      id: '/products/$product'
      path: '/products/$product'
      fullPath: '/products/$product'
      preLoaderRoute: typeof ProductsProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CatalogueRouteChildren {
  CataloguePrintRoute: typeof CataloguePrintRoute
}

const CatalogueRouteChildren: CatalogueRouteChildren = {
  CataloguePrintRoute: CataloguePrintRoute,
}

const CatalogueRouteWithChildren = CatalogueRoute._addFileChildren(
  CatalogueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CatalogueRoute: CatalogueRouteWithChildren,
  ContactRoute: ContactRoute,
  CorporateGiftingRoute: CorporateGiftingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  CollectionsCategoryRoute: CollectionsCategoryRoute,
  OccasionsOccasionRoute: OccasionsOccasionRoute,
  ProductsProductRoute: ProductsProductRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  OccasionsIndexRoute: OccasionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
